### PR TITLE
Add some documentation

### PR DESCRIPTION
**Pull request by JaceCear**
Hey there, Ollie!

I've pinged you on Twitter, but I guess you're not using it much?
Anyway, I've added a few notable pieces of data I've learned over the years to this project, they might be of help to you.

If you wanna know some other stuff I learned, (or details on some of those I added) feel free to check out the thread I did, detailing some stuff:
https://twitter.com/JaceCear/status/1362833958862479366

I don't think I'll be an active participant here, but that's just depending on some life circumstances.

Can't wait to see what will come out of this project!

### CODE REVIEW

**Comment by freshollie** [comment]
This is amazing! Thanks!

And yeah my twitter dms were not open, email or discord are best to reach out to me on, I’m in most of the decomp communities. 

There is some conflicts as I pushed a change last night which also edited the data definitions.

**Comment by freshollie** [comment]
Hmm, merged this cos CI passed, but seems PR target was on the wrong files so failing on main now. Looks like you didn't update the types in the C files too. Will see if I can fix

**Comment by JaceCear** [comment]
Oh, really? It compiled, so I assumed everything was fine.

Again, Git is not exactly my friend when it comes to merge conflicts. ^^

**Comment by freshollie** [comment]
```
src/sprite.c: In function `sub_8002A3C':
src/sprite.c:13: dereferencing pointer to incomplete type
src/sprite.c:14: dereferencing pointer to incomplete type
src/sprite.c:15: dereferencing pointer to incomplete type
src/sprite.c:16: dereferencing pointer to incomplete type
src/sprite.c:24: dereferencing pointer to incomplete type
src/sprite.c:25: dereferencing pointer to incomplete type
src/sprite.c:26: dereferencing pointer to incomplete type
src/sprite.c:34: dereferencing pointer to incomplete type
src/sprite.c:37: dereferencing pointer to incomplete type
src/sprite.c:38: dereferencing pointer to incomplete type
src/sprite.c:39: dereferencing pointer to incomplete type
```

On master atm cos the types are wrong

**Comment by freshollie** [comment]
I've reverted the changes, as it didn't match even when I reverted the header to test. May have been a mistake when you merged.

If you don't have time I'll try and reapply these changes myself one by one

**Pull request merged**
