### PR TITLE
Update UI Positions of Timer/1-Up

### PR DESCRIPTION
**Pull request by BlueSpeedsterYT**
The most simplest thing to do, feel free to improve it if need be.

### CODE REVIEW

**Comment by BlueSpeedsterYT** [comment]
God.
The reason why the game couldn't match the source game is because I made one of the HUD pieces be in 141 instead of 99...
Now that it's fixed, I am now very scared of the game.

**Review by JaceCear — APPROVED** [review]
Great additions, thank you!

**Comment by BlueSpeedsterYT** [comment]
You know... I forgot about something in the code. Line 173, still has the raw value for the life icon's Y position.

**Comment by BlueSpeedsterYT** [comment]
You know... I forgot about something in the code. Line 173, still has the raw value for the life icon's Y position.

**Pull request merged**
