### PR TITLE
Document procedures in game_6.s and general documentation

### PR DESCRIPTION
**Pull request by JaceCear**

### CODE REVIEW

**Review by freshollie — APPROVED** [review]
Very interesting! Not sure if you are done, but great documenting :D

**Comment by JaceCear** [comment]
Not quite done, but making progress! ^^

**Comment by JaceCear** [comment]
Can we already decide on the name or is it too early?
What about `properties`, `gfx_properties` or `settings`?
The latter kinda sounds wrong to me intuitively, but it might work?
https://github.com/freshollie/sa2/blob/320f325ddfc46a70187c3c32733805668804d869/include/sprite.h#L120

**Comment by JaceCear** [comment]
This should be `hitboxes`, I don't think that's a bad name?
https://github.com/freshollie/sa2/blob/320f325ddfc46a70187c3c32733805668804d869/include/sprite.h#L157

**Comment by JaceCear** [comment]
Now I feel like it's mergable, unless there's something you'd like to see changed @freshollie! :D

**Pull request merged**
